name: Keep the versions up-to-date ☕️

on:
  release:
    types: [published, edited]

jobs:
  actions-tagger:
    runs-on: self-hosted
    steps:
      - uses: Actions-R-Us/actions-tagger@latest
        with:
          publish_latest_tag: true
