name: Keep the versions up-to-date ☕️

on:
  release:
    types: [published, edited]

concurrency:
  group: tagger-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  actions-tagger:
    runs-on: ubuntu-latest
    steps:
      - uses: Actions-R-Us/actions-tagger@latest
        with:
          publish_latest_tag: true
