---
name: WASM 🧭

on:
  workflow_call:
    inputs:
      package-subdirectory:
        description: Subdirectory in the repository, where the R package is located.
        required: false
        type: string
        default: ""

jobs:
  wasm:
    name: WASM 🧭
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Get branch names 🌿
        id: branch-name
        uses: tj-actions/branch-names@e497ceb8ccd43fd9573cf2e375216625bc411d1f # v9.0.0

      - name: Checkout repo 🛎
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: ${{ steps.branch-name.outputs.current_branch }}
          path: ${{ github.event.repository.name }}

      - name: Get package name 📦
        run: |
          echo "PKGNAME=$(echo $(awk -F: '/Package:/{gsub(/[ ]+/,"") ; print $2}' DESCRIPTION))" >> $GITHUB_ENV
        shell: bash
        working-directory: ${{ github.event.repository.name }}/${{ inputs.package-subdirectory }}

      - name: Build WASM packages 🧭
        uses: r-wasm/actions/build-rwasm@193ba7b53fed3d8daaf59a8249c3f4a7f31ba728 # v1
        with:
          packages: |
            ${{ github.repository_owner }}/${{ env.PKGNAME }}@${{ steps.branch-name.outputs.tag }}

      - name: Upload WASM packages ⬆
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: wasm-${{ env.PKGNAME }}
          path: |
            _site/bin/emscripten/contrib/*/${{ env.PKGNAME }}*.tgz
            _site/src/contrib/${{ env.PKGNAME }}*.tar.gz

      - name: Check if release exists ⚙️
        id: check-if-release-exists
        uses: insightsengineering/release-existence-action@v1

      - name: Download artifact ⏬
        if: >-
          steps.check-if-release-exists.outputs.release-exists == 'true'
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          name: wasm-${{ env.PKGNAME }}
          path: wasm-${{ env.PKGNAME }}

      - name: Prepare WASM release artifact 🗜️
        if: >-
          steps.check-if-release-exists.outputs.release-exists == 'true'
        run: |
          zip -r9 wasm-${{ env.PKGNAME }}.zip wasm-${{ env.PKGNAME }}

      - name: Upload WASM build to release 🔼
        if: >-
          steps.check-if-release-exists.outputs.release-exists == 'true'
        uses: svenstaro/upload-release-action@29e53e917877a24fad85510ded594ab3c9ca12de # v2
        with:
          file: ./wasm-${{ env.PKGNAME }}.zip
          asset_name: wasm-${{ env.PKGNAME }}.zip
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          overwrite: true
